apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  application-name: quarkus-crud-demo
  org: rafaeltuelho.github.io

resources:
- pg-cluster.yaml
- deployment.yaml
- service.yaml
- route.yaml
- service-binding.yaml
# - post-sync-job.yaml
# - pre-sync-job.yaml



