apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devspaces-quarkus-crud-demo
    app.kubernetes.io/version: java11-latest
    app.openshift.io/runtime: quarkus
  name: quarkus-crud-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-crud-demo
    app.kubernetes.io/version: java11-latest
  type: ClusterIP
