# namePrefix: dev-
commonLabels:
  variant: development



# apply a patch to replace the Host of the Route
#- patch: |-
#    - op: replace
#      path: /spec/host
#      value: art-test.apps-crc.testing
#  target:
#    kind: Route
# this patch needs to be done, because kustomize does not change 
# the route target service name
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: quarkus-crud-demo
  target:
    kind: Route
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:231d87efad928061b369b8b8323b6e6f09411688c0d7107ab196b5913cedbf40
  name: quay.io/rafaeltuelho/devspaces-quarkus-crud-demo:latest
  newName: quay.io/rafaeltuelho/devspaces-quarkus-crud-demo
