namePrefix: dev-
commonLabels:
  variant: development



# apply a patch to replace the Host of the Route
#- patch: |-
#    - op: replace
#      path: /spec/host
#      value: art-test.apps-crc.testing
#  target:
#    kind: Route
# this patch needs to be done, because kustomize does not change 
# the route target service name
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-simple
  target:
    kind: Route
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:eb2c8d1472eeff3059ac4c437e96cfd8a985d9c3779205679deb888544dbdaf6
  name: quay.io/rafaeltuelho/devspaces-quarkus-crud-demo:latest
  newName: quay.io/rafaeltuelho/devspaces-quarkus-crud-demo
- digest: sha256:97a32ce12b1bcd53b7ff5b03b7bc3fc75d4c42b97141f939802057b113fcff7d
  name: quay.io/rafaeltuelho/quarkus-crud-demo:latest
  newName: quay.io/rafaeltuelho/quarkus-crud-demo
